# ============================================================
# Composite Action: aws-auth
#
# Configures AWS credentials using static access keys.
# Centralises the configure-aws-credentials step so that all
# deploy, verify and SIT jobs share a single, auditable pin.
#
# TODO: Migrate to OIDC when IAM Identity Provider is configured.
# ============================================================

name: Configure AWS credentials
description: "Configures AWS credentials using static access keys for the current job."

inputs:
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-region:
    description: "AWS region to target"
    required: true

runs:
  using: composite
  steps:
    - name: Mask AWS credentials
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.aws-access-key-id }}"
        echo "::add-mask::${{ inputs.aws-secret-access-key }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@5579c002bb4778aa43395ef1df492868a9a1c83f # v4.0.2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
