# ============================================================
# Composite Action: aws-auth
#
# Configures AWS credentials via OIDC for GitHub Actions jobs.
# Centralises the configure-aws-credentials step so that all
# deploy, verify and SIT jobs share a single, auditable pin.
# ============================================================

name: Configure AWS credentials (OIDC)
description: "Assumes an IAM role via OIDC and configures AWS credentials for the current job."

inputs:
  role-to-assume:
    description: "ARN of the IAM role to assume via OIDC"
    required: true
  aws-region:
    description: "AWS region to target"
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
